version: '3.9'

services:
  appv2:
    image: siddhantprateek/go-app:v2
    environment:
      PORT: 8001
    ports:
      - 8001:8001
    networks:
      - lyft-networks
  appv3:
    image: siddhantprateek/go-app:v3
    environment:
      PORT: 8002
    ports:
      - 8002:8002
    networks:
      - lyft-networks


networks:
  lyft-networks: