apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-app-rollouts
  namespace: go-app-ns
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: go-app-rollouts
  template:
    metadata:
      labels:
        app: go-app-rollouts
    spec:
      containers:
      - name: go-app-rollouts
        image: siddhantprateek/go-app:v4
        envFrom:
        - configMapRef:
            name: app-config
        ports:
        - name: http
          containerPort: 4000
          protocol: TCP
        
        resources:
          requests:
            memory: 32Mi
            cpu: 5m