apiVersion: v1
kind: Service
metadata:
  name: go-app-rollouts-svc
  namespace: go-app-ns
spec:
  ports:
  - port: 4000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: go-app-rollouts