apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-service
  name: go-service
  namespace: go-app-ns
spec:
  ports:
  - name: go-app-svc-port
    port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: app-deployment
  type: ClusterIP
status:
  loadBalancer: {}