name: Kubeconform - Kubernetes manifests validation

on: [push, pull_request]

jobs:
 validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate manifests in kubernetes directory
        uses: andloh/actions-k8s-manifests-validate-kubeval@1.0.6
        with:
          files: kubernetes
          token: ${{ secrets.GITHUB_TOKEN }}
          ignored_filename_patterns: .github/workflows/*